version: "3.9"
services:
  client:
    build:
      context: ./client
    command: sh -c "sleep 0.1s ; python3 ./client.py"
    expose:
      - "65432"

  server:
    build: 
      context: ./server
    command: python3 ./server.py
    expose:
      - "65432"
    hostname: "server"