version: "3.9"
services:
  client:
    build: ./client/
    command: sh -c "sleep 0.1s ; python3 ./client.py"

  server:
    build: ./Server/
    command: python3 ./server.py
    expose:
      - '65432'
      - '21'